#!/usr/bin/env python3
"""
run_active_learning.py
Active learning over Enamine50k using pre-extracted MUBen backbone embeddings.

Sources of truth:
  pool + order : molpal/libraries/Enamine50k.csv.gz
  oracle scores: data/Enamine50k_scores.csv.gz
  embeddings   : results/embed/Enamine50k/{backbone}_embeddings.npz
                 (generated by muben/extract_embeddings.py)
"""

import sys
import json
import pickle
import argparse
import time
from pathlib import Path

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset

ROOT = Path(__file__).resolve().parent

# Imported lazily when --finetune is used so the script stays importable
# even without muben installed in non-finetuning runs.
try:
    from backbone_finetuner import BackboneFinetuner, MODEL_ZOO as _MODEL_ZOO
except ImportError:
    BackboneFinetuner = None
    _MODEL_ZOO = ROOT / "models"

# ── paths ─────────────────────────────────────────────────────────────────────
EMBED_DIR  = ROOT / "results" / "embed"
DATA_DIR   = ROOT / "data"
LIBRARY_DIR = ROOT / "molpal" / "libraries"
RUNS_DIR   = ROOT / "runs"
RUNS_DIR.mkdir(exist_ok=True)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")


# ==============================================================================
# DATA
# ==============================================================================

def load_embeddings(backbone: str, dataset: str) -> tuple[np.ndarray, list[str]]:
    npz_path = EMBED_DIR / dataset / f"{backbone}_embeddings.npz"
    assert npz_path.exists(), (
        f"Missing {npz_path}\n"
        f"Run:  python muben/extract_embeddings.py  first."
    )
    data = np.load(npz_path, allow_pickle=True)
    embeddings = data["embeddings"].astype(np.float32)   # (N, D)
    smiles     = data["smiles"].tolist()                 # [N]
    print(f"[embeddings] {backbone}: {embeddings.shape}")
    return embeddings, smiles


def load_library_smiles(dataset: str) -> list[str]:
    """Load SMILES from the molpal library (single source of truth for pool order)."""
    lib = LIBRARY_DIR / f"{dataset}.csv.gz"
    assert lib.exists(), f"Library not found: {lib}"
    df = pd.read_csv(lib)
    df.columns = df.columns.str.strip().str.lower()
    smi_col = next(c for c in df.columns if "smiles" in c)
    smiles = df[smi_col].dropna().tolist()
    print(f"[library] {lib.name}: {len(smiles):,} SMILES")
    return smiles


def load_oracle(dataset: str) -> dict[str, float]:
    gz = DATA_DIR / f"{dataset}_scores.csv.gz"
    assert gz.exists(), f"Missing oracle file: {gz}"
    df = pd.read_csv(gz)
    df.columns = df.columns.str.strip().str.lower()
    smi_col   = next(c for c in df.columns if "smiles" in c)
    score_col = next(c for c in df.columns if "score"  in c)
    oracle = dict(zip(df[smi_col], df[score_col]))
    print(f"[oracle] {gz.name}: {len(oracle):,} molecules  "
          f"range [{df[score_col].min():.2f}, {df[score_col].max():.2f}] kcal/mol")
    return oracle


def build_pool(
    backbone: str,
    dataset:  str,
) -> tuple[np.ndarray, list[str], dict[str, float]]:
    """
    Intersect embedding index with oracle, return aligned (matrix, smiles, oracle).
    """
    embeddings, embed_smiles = load_embeddings(backbone, dataset)
    oracle = load_oracle(dataset)

    smi2row = {s: i for i, s in enumerate(embed_smiles)}

    # keep molecules that have both an embedding and a docking score
    usable = [s for s in embed_smiles if s in oracle]
    missing_score = len(embed_smiles) - len(usable)
    if missing_score:
        print(f"[pool] {missing_score} molecules have no oracle score — skipped")

    rows   = [smi2row[s] for s in usable]
    matrix = embeddings[rows]

    print(f"[pool] usable={len(usable):,}  embed_dim={matrix.shape[1]}")
    return matrix, usable, oracle


# ==============================================================================
# SURROGATE MODEL
# ==============================================================================

class MLPHead(nn.Module):
    def __init__(self, in_dim: int, hidden: int, dropout: float):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(in_dim, hidden),
            nn.LayerNorm(hidden),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden, hidden // 2),
            nn.LayerNorm(hidden // 2),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden // 2, 1),
        )

    def forward(self, x):
        return self.net(x).squeeze(-1)


class Surrogate:
    def __init__(self, in_dim, uq="mc_dropout", hidden=512,
                 dropout=0.2, n_ensemble=5, lr=3e-4):
        self.uq      = uq
        self.dropout = dropout
        self._ym = self._ys = None   # running normalisation stats

        if uq == "ensemble":
            self.models = [MLPHead(in_dim, hidden, 0.0).to(DEVICE)
                           for _ in range(n_ensemble)]
        else:
            self.models = [MLPHead(in_dim, hidden, dropout).to(DEVICE)]

        self.opts = [torch.optim.AdamW(m.parameters(), lr=lr)
                     for m in self.models]

    # ── training ──────────────────────────────────────────────────────────────
    def fit(self, X: np.ndarray, y: np.ndarray, epochs=80, batch=256):
        self._ym = y.mean(); self._ys = y.std() + 1e-8
        yn = (y - self._ym) / self._ys

        Xt = torch.tensor(X,  dtype=torch.float32)
        yt = torch.tensor(yn, dtype=torch.float32)

        use_amp = DEVICE.type == "cuda"
        amp_dtype = torch.bfloat16 if (use_amp and torch.cuda.is_bf16_supported()) else torch.float16

        for model, opt in zip(self.models, self.opts):
            loader = DataLoader(TensorDataset(Xt, yt), batch_size=batch, shuffle=True)
            model.train()
            scaler = torch.amp.GradScaler("cuda", enabled=use_amp)   # fixed deprecation
            for _ in range(epochs):
                for xb, yb in loader:
                    xb, yb = xb.to(DEVICE), yb.to(DEVICE)
                    opt.zero_grad()
                    with torch.autocast(device_type=DEVICE.type,
                                        dtype=amp_dtype,
                                        enabled=use_amp):             # no-op on CPU
                        loss = nn.functional.mse_loss(model(xb), yb)
                    scaler.scale(loss).backward()
                    scaler.step(opt); scaler.update()



    # ── inference ─────────────────────────────────────────────────────────────
    def predict(self, X: np.ndarray, T=30, batch=1024) -> tuple[np.ndarray, np.ndarray]:
        Xt = torch.tensor(X, dtype=torch.float32)
        use_amp   = DEVICE.type == "cuda"                                    # add this
        amp_dtype = torch.bfloat16 if (use_amp and torch.cuda.is_bf16_supported()) else torch.float16  # add this

        def _run(model):
            preds = []
            with torch.no_grad():
                for (xb,) in DataLoader(TensorDataset(Xt), batch_size=batch, shuffle=False):
                    xb = xb.to(DEVICE)
                    with torch.autocast(device_type=DEVICE.type, dtype=amp_dtype, enabled=use_amp):
                        preds.append(model(xb).float().cpu().numpy())
            return np.concatenate(preds)

        if self.uq == "ensemble":
            samples = np.stack([_run(m) for m in
                                (m.eval() or m for m in self.models)])
        else:
            self.models[0].train()   # keep dropout active
            samples = np.stack([_run(self.models[0]) for _ in range(T)])

        mu_n, sig_n = samples.mean(0), samples.std(0)
        # denormalise mean; sigma stays in normalised space (only used for ranking)
        return mu_n * self._ys + self._ym, sig_n


# ==============================================================================
# ACQUISITION FUNCTIONS  (surrogate always maximises)
# ==============================================================================

def acq_ucb(mu, sigma, beta=2.0, **_):      return mu + beta * sigma
def acq_greedy(mu, sigma, **_):             return mu
def acq_thompson(mu, sigma, **_):           return np.random.normal(mu, sigma)

ACQ = {"ucb": acq_ucb, "greedy": acq_greedy, "thompson": acq_thompson}


# ==============================================================================
# ACTIVE LEARNING LOOP
# ==============================================================================

class ALExplorer:
    def __init__(self, embed_matrix, pool_smiles, oracle, surrogate,
                 acq_fn, init_size=200, batch_size=100,
                 n_rounds=15, run_dir=None,
                 finetuner=None, finetune_epochs=10,
                 finetune_lr_backbone=1e-5, finetune_lr_head=1e-4):
        self.X          = embed_matrix          # (N, D)  — refreshed each round when finetuner is set
        self.smiles     = np.array(pool_smiles) # [N]
        self.oracle     = oracle                # smiles → kcal/mol (lower = better)
        self.surrogate  = surrogate
        self.acq_fn     = acq_fn
        self.batch_size = batch_size
        self.n_rounds   = n_rounds
        self.run_dir    = run_dir or RUNS_DIR / "al_run"
        self.run_dir.mkdir(parents=True, exist_ok=True)

        # optional online backbone finetuner
        self.finetuner           = finetuner
        self.finetune_epochs     = finetune_epochs
        self.finetune_lr_backbone = finetune_lr_backbone
        self.finetune_lr_head    = finetune_lr_head

        # docking scores are negative: negate so surrogate maximises
        self._sign = -1.0

        rng      = np.random.default_rng(42)
        init_idx = rng.choice(len(self.smiles), init_size, replace=False)

        self.labeled_idx    = set(init_idx.tolist())
        self.labeled_scores = {self.smiles[i]: oracle[self.smiles[i]]
                               for i in init_idx}

        print(f"[init] {init_size} random molecules  "
              f"best={self._best():.3f} kcal/mol")

    def _best(self):
        return min(self.labeled_scores.values())

    def _recall(self, k: int) -> float:
        top_k = set(s for s, _ in
                    sorted(self.oracle.items(), key=lambda x: x[1])[:k])
        return sum(1 for s in self.labeled_scores if s in top_k) / k

    def run(self) -> list[dict]:
        history = []

        for rnd in range(self.n_rounds):
            t0 = time.perf_counter()

            # 0. [optional] finetune backbone on labeled set, then refresh embeddings
            if self.finetuner is not None:
                labeled_smi = [self.smiles[i] for i in self.labeled_idx]
                labeled_sc  = np.array(
                    [self.labeled_scores[s] for s in labeled_smi], dtype=np.float32
                )
                self.finetuner.finetune(
                    labeled_smi, labeled_sc,
                    n_epochs    = self.finetune_epochs,
                    lr_backbone = self.finetune_lr_backbone,
                    lr_head     = self.finetune_lr_head,
                )
                self.X = self.finetuner.extract_pool_embeddings()

            # 1. labeled embeddings + scores (negated for maximisation)
            idx  = list(self.labeled_idx)
            X_tr = self.X[idx]
            y_tr = self._sign * np.array(
                [self.labeled_scores[self.smiles[i]] for i in idx],
                dtype=np.float32)

            # 2. train surrogate
            self.surrogate.fit(X_tr, y_tr)

            # 3. predict unlabeled pool
            mask        = np.ones(len(self.smiles), bool)
            for i in self.labeled_idx:
                mask[i] = False
            pool_idx    = np.where(mask)[0]
            mu, sigma   = self.surrogate.predict(self.X[pool_idx])

            # 4. acquire top-k
            scores      = self.acq_fn(mu, sigma)
            top_local   = np.argsort(scores)[::-1][: self.batch_size]
            selected    = pool_idx[top_local]

            # 5. query oracle
            for i in selected:
                smi = self.smiles[i]
                self.labeled_scores[smi] = self.oracle[smi]
                self.labeled_idx.add(int(i))

            # 6. metrics
            k1pct   = max(1, len(self.smiles) // 100)
            recall  = self._recall(k1pct)
            elapsed = time.perf_counter() - t0

            print(f"  Round {rnd+1:02d}/{self.n_rounds}  "
                  f"labeled={len(self.labeled_idx):,}  "
                  f"best={self._best():.3f} kcal/mol  "
                  f"top-1% recall={recall:.1%}  "
                  f"({elapsed:.1f}s)")

            record = dict(round=rnd+1, n_labeled=len(self.labeled_idx),
                          best_score=float(self._best()),
                          top1pct_recall=float(recall))
            history.append(record)
            self._checkpoint(rnd + 1, record)

        self._save_final(history)
        return history

    def _checkpoint(self, rnd, record):
        d = self.run_dir / f"iter_{rnd}"
        d.mkdir(exist_ok=True)
        (d / "state.json").write_text(json.dumps(record, indent=2))
        with open(d / "scores.pkl", "wb") as f:
            pickle.dump(dict(self.labeled_scores), f)

    def _save_final(self, history):
        pd.DataFrame(
            sorted(self.labeled_scores.items(), key=lambda x: x[1]),
            columns=["smiles", "score"]
        ).to_csv(self.run_dir / "all_explored_final.csv", index=False)
        (self.run_dir / "history.json").write_text(json.dumps(history, indent=2))
        print(f"\n[done] {self.run_dir}")


# ==============================================================================
# ENTRY POINT
# ==============================================================================

def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--dataset",    default="Enamine50k",
                   choices=["Enamine10k", "Enamine50k", "EnamineHTS"])
    p.add_argument("--backbone",   default="unimol",
                   choices=["unimol", "grover", "molformer"])
    p.add_argument("--uq",         default="mc_dropout",
                   choices=["mc_dropout", "ensemble"])
    p.add_argument("--acq",        default="ucb",
                   choices=["ucb", "greedy", "thompson"])
    p.add_argument("--init-size",  type=int, default=200)
    p.add_argument("--batch-size", type=int, default=100)
    p.add_argument("--n-rounds",   type=int, default=15)
    p.add_argument("--hidden",     type=int, default=512)
    p.add_argument("--dropout",    type=float, default=0.2)
    p.add_argument("--n-ensemble", type=int, default=5)
    p.add_argument("--epochs",     type=int, default=80)
    p.add_argument("--seed",       type=int, default=42)
    # ── online backbone finetuning ────────────────────────────────────────────
    p.add_argument("--finetune",    action="store_true",
                   help="Finetune backbone at each AL round (requires muben)")
    p.add_argument("--finetune-epochs",      type=int,   default=10,
                   help="Gradient epochs per AL round when finetuning")
    p.add_argument("--finetune-lr-backbone", type=float, default=1e-5,
                   help="Backbone learning rate during finetuning")
    p.add_argument("--finetune-lr-head",     type=float, default=1e-4,
                   help="Regression head learning rate during finetuning")
    return p.parse_args()


def main():
    args = parse_args()
    np.random.seed(args.seed)
    torch.manual_seed(args.seed)

    print(f"\n{'='*60}")
    print(f"  dataset={args.dataset}  backbone={args.backbone}")
    print(f"  uq={args.uq}  acq={args.acq}  device={DEVICE}")
    print(f"  finetune={args.finetune}"
          + (f"  ft_epochs={args.finetune_epochs}" if args.finetune else ""))
    print(f"{'='*60}\n")

    # ── build pool ─────────────────────────────────────────────────────────────
    if args.finetune:
        if BackboneFinetuner is None:
            raise RuntimeError("backbone_finetuner.py could not be imported. "
                               "Make sure muben is on sys.path.")

        # Pool = library SMILES intersected with oracle
        library_smiles = load_library_smiles(args.dataset)
        oracle         = load_oracle(args.dataset)
        pool_smiles    = [s for s in library_smiles if s in oracle]
        print(f"[pool] {len(pool_smiles):,} molecules (library ∩ oracle)")

        finetuner = BackboneFinetuner(
            backbone     = args.backbone,
            dataset_name = args.dataset,
            pool_smiles  = pool_smiles,
            model_zoo    = _MODEL_ZOO,
        )
        # Initial embeddings come from the pretrained (not yet finetuned) backbone
        matrix = finetuner.extract_pool_embeddings()
    else:
        # Default path: load pre-extracted static embeddings
        matrix, pool_smiles, oracle = build_pool(args.backbone, args.dataset)
        finetuner = None

    # ── surrogate ──────────────────────────────────────────────────────────────
    surrogate = Surrogate(
        in_dim     = matrix.shape[1],
        uq         = args.uq,
        hidden     = args.hidden,
        dropout    = args.dropout,
        n_ensemble = args.n_ensemble,
    )

    # ── run dir (mark finetuned runs separately) ───────────────────────────────
    run_suffix = f"al_{args.dataset}_{args.backbone}_{args.uq}_{args.acq}"
    if args.finetune:
        run_suffix += "_finetuned"
    run_dir = RUNS_DIR / run_suffix

    explorer = ALExplorer(
        embed_matrix      = matrix,
        pool_smiles       = pool_smiles,
        oracle            = oracle,
        surrogate         = surrogate,
        acq_fn            = ACQ[args.acq],
        init_size         = args.init_size,
        batch_size        = args.batch_size,
        n_rounds          = args.n_rounds,
        run_dir           = run_dir,
        finetuner         = finetuner,
        finetune_epochs   = args.finetune_epochs,
        finetune_lr_backbone = args.finetune_lr_backbone,
        finetune_lr_head     = args.finetune_lr_head,
    )

    history = explorer.run()

    print(f"\n{'Round':>6} {'Labeled':>8} {'Best (kcal/mol)':>16} {'Top-1% recall':>14}")
    print("-" * 50)
    for r in history:
        print(f"{r['round']:>6} {r['n_labeled']:>8,} "
              f"{r['best_score']:>16.3f} {r['top1pct_recall']:>13.1%}")


if __name__ == "__main__":
    main()